const currencyInfo = {
SAR:{name:"Saudi Riyal",flag:"🇸🇦"},
EGP:{name:"Egyptian Pound",flag:"🇪🇬"},
USD:{name:"US Dollar",flag:"🇺🇸"},
EUR:{name:"Euro",flag:"🇪🇺"},
GBP:{name:"British Pound",flag:"🇬🇧"},
AED:{name:"UAE Dirham",flag:"🇦🇪"},
KWD:{name:"Kuwaiti Dinar",flag:"🇰🇼"},
QAR:{name:"Qatari Riyal",flag:"🇶🇦"},
BHD:{name:"Bahraini Dinar",flag:"🇧🇭"},
OMR:{name:"Omani Rial",flag:"🇴🇲"},
JOD:{name:"Jordanian Dinar",flag:"🇯🇴"},
TRY:{name:"Turkish Lira",flag:"🇹🇷"},
INR:{name:"Indian Rupee",flag:"🇮🇳"},
JPY:{name:"Japanese Yen",flag:"🇯🇵"},
CNY:{name:"Chinese Yuan",flag:"🇨🇳"},
CAD:{name:"Canadian Dollar",flag:"🇨🇦"},
AUD:{name:"Australian Dollar",flag:"🇦🇺"},
CHF:{name:"Swiss Franc",flag:"🇨🇭"},
SEK:{name:"Swedish Krona",flag:"🇸🇪"},
NOK:{name:"Norwegian Krone",flag:"🇳🇴"},
DKK:{name:"Danish Krone",flag:"🇩🇰"},
RUB:{name:"Russian Ruble",flag:"🇷🇺"},
BRL:{name:"Brazilian Real",flag:"🇧🇷"},
ZAR:{name:"South African Rand",flag:"🇿🇦"},
MXN:{name:"Mexican Peso",flag:"🇲🇽"},
SGD:{name:"Singapore Dollar",flag:"🇸🇬"},
HKD:{name:"Hong Kong Dollar",flag:"🇭🇰"},
KRW:{name:"South Korean Won",flag:"🇰🇷"},
NZD:{name:"New Zealand Dollar",flag:"🇳🇿"},
PKR:{name:"Pakistani Rupee",flag:"🇵🇰"},
BDT:{name:"Bangladeshi Taka",flag:"🇧🇩"}
};
