const currencyInfo = {
    USD: { name: "الدولار الأمريكي", code: "US" },
    EUR: { name: "اليورو الأوروبي", code: "EU" },
    SAR: { name: "الريال السعودي", code: "SA" },
    EGP: { name: "الجنيه المصري", code: "EG" },
    AED: { name: "الدرهم الإماراتي", code: "AE" },
    KWD: { name: "الدينار الكويتي", code: "KW" },
    QAR: { name: "الريال قطر", code: "QA" },
    BHD: { name: "الدينار البحريني", code: "BH" },
    OMR: { name: "الريال العماني", code: "OM" },
    JOD: { name: "الدينار الأردني", code: "JO" },
    GBP: { name: "الجنيه الإسترليني", code: "GB" },
    TRY: { name: "الليرة التركية", code: "TR" },
    CAD: { name: "الدولار الكندي", code: "CA" },
    AUD: { name: "الدولار الأسترالي", code: "AU" },
    CHF: { name: "الفرنك السويسري", code: "CH" },
    CNY: { name: "اليوان الصيني", code: "CN" },
    JPY: { name: "الين الياباني", code: "JP" },
    INR: { name: "الروبية الهندية", code: "IN" },
    RUB: { name: "الروبل الروسي", code: "RU" },
    BRL: { name: "الريال البرازيلي", code: "BR" },
    ZAR: { name: "الراند الجنوب أفريقي", code: "ZA" },
    MXN: { name: "البيزو المكسيكي", code: "MX" },
    SGD: { name: "الدولار السنغافوري", code: "SG" },
    HKD: { name: "دولار هونغ كونغ", code: "HK" },
    KRW: { name: "الوون الكوري الجنوبي", code: "KR" },
    NZD: { name: "الدولار النيوزيلندي", code: "NZ" },
    PKR: { name: "الروبية الباكستانية", code: "PK" },
    BDT: { name: "التاكا البنغلاديشية", code: "BD" },
    LBP: { name: "الجنيه اللبناني", code: "LB" },
    LYD: { name: "الدينار الليبي", code: "LY" },
    MAD: { name: "الدرهم المغربي", code: "MA" },
    TND: { name: "الدينار التونسي", code: "TN" },
    DZD: { name: "الدينار الجزائري", code: "DZ" },
    IQD: { name: "الدينار العراقي", code: "IQ" },
    YER: { name: "الريال اليمني", code: "YE" },
    SDG: { name: "الجنيه السوداني", code: "SD" },
    SYP: { name: "الليرة السورية", code: "SY" }
};
